--测试表
DROP TABLE IF EXISTS SYS_TEST;
CREATE TABLE SYS_TEST(
    ID BIGINT IDENTITY PRIMARY KEY,
    NAME VARCHAR(255),
    AGE TINYINT,
    CASH DECIMAL(20, 2),
    UNIQUE_CODE UUID,
    BIRTHDATE DATE,
    CREATE_TIME TIMESTAMP DEFAULT SYSDATE
);

--日志表：用户登录记录
DROP TABLE IF EXISTS LOG_VISIT;
CREATE TABLE LOG_VISIT(
    ID BIGINT IDENTITY PRIMARY KEY,
    NAME VARCHAR(255),
    REMARK VARCHAR(255),
    CREATE_TIME TIMESTAMP DEFAULT SYSDATE
); 
